language: node_js

node_js:
  - v6

branches:
  only:
    - master

script: npm run test && npm run test:cov

addons:
  code_climate:
    repo_token: $CODE_CLIMATE

before_install:
  - "npm install react firebase lodash redux react-redux"

after_success:
  - npm install -g codeclimate-test-reporter
  - codeclimate-test-reporter < coverage/*/lcov.info
