language: node_js

node_js:
- 5.9.0

sudo: false

branches:
  only:
    - master

cache:
  directories:
    - node_modules

script:
  - npm run lint
  - npm run build

deploy:
  skip_cleanup: true
  provider: heroku
  api_key:
    secure: $HEROKU
  app: devshare-stg
